# Generated by Django 3.2.23 on 2024-02-08 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_country_street_address2',
            new_name='default_street_address2',
        ),
    ]
