# Generated by Django 3.2.23 on 2024-02-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20240207_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='original_bag',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(default=' ', max_length=254),
        ),
    ]
