# Generated by Django 3.2.23 on 2024-01-31 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_friendly_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
